# Generated by Django 5.2.12 on 2026-04-04 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('buy_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'buy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('province_id', models.CharField(max_length=45)),
                ('district_id', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'job',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LedgerType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'ledger_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('province_id', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'supplier',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'warehouse',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('ledger_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=19)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='market_app.customer')),
                ('reference_buy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='market_app.buy')),
                ('ledger_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market_app.ledgertype')),
            ],
            options={
                'db_table': 'ledger',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LedgerPayment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(default='cash', max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='market_app.ledger')),
            ],
            options={
                'db_table': 'ledger_payment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market_app.category')),
            ],
            options={
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BuyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=19)),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market_app.buy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market_app.product')),
            ],
            options={
                'db_table': 'buy_item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('sell_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('payment_type', models.CharField(default='cash', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market_app.customer')),
            ],
            options={
                'db_table': 'sell',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ledger',
            name='reference_sell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='market_app.sell'),
        ),
        migrations.CreateModel(
            name='SellItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=19)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market_app.product')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market_app.sell')),
            ],
            options={
                'db_table': 'sell_item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('stuff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('salary', models.DecimalField(decimal_places=6, max_digits=19)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market_app.job')),
            ],
            options={
                'db_table': 'stuff',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ledger',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='market_app.supplier'),
        ),
        migrations.AddField(
            model_name='buy',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market_app.supplier'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=6, max_digits=19)),
                ('expire_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market_app.product')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='market_app.buy')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market_app.warehouse')),
            ],
            options={
                'db_table': 'stock',
                'managed': True,
            },
        ),
    ]
