# Generated by Django 6.0.4 on 2026-04-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0003_report_reportattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
